In [2]:
import os
import torch
import numpy as np
import imageio
from pprint import pprint
import matplotlib.pyplot as plt
import run_nerf
import run_nerf_helpers

### Load trained network weights

In [3]:
basedir = './logs'
expname = 'lego_example'

config = os.path.join(basedir, expname, 'config.txt')

parser = run_nerf.config_parser()
ft_str = '' 
ft_str = '--ft_path {}'.format(os.path.join(basedir, expname, '020000.tar'))
args = parser.parse_args('--config {} '.format(config) + ft_str)

# Create nerf model
_, render_kwargs_test, start, grad_vars, models = run_nerf.create_nerf(args)

bds_dict = {
    'near': 2.,
    'far': 6.,
}
render_kwargs_test.update(bds_dict)

net_fn = render_kwargs_test['network_query_fn']
print(net_fn)

# Render an overhead view to check model was loaded correctly
c2w = torch.Tensor(np.eye(4)[:3,:4].astype(np.float32)) # identity pose matrix
c2w[2,-1] = 4.
H, W, focal = 800, 800, 1200.
down = 8
K = np.array([
            [focal/down, 0, 0.5*W//down],
            [0, focal/down, 0.5*H//down],
            [0, 0, 1]
        ])
test = run_nerf.render(H//down, W//down, K, focal/down, c2w=c2w, **render_kwargs_test)
img = np.clip(test[0],0,1)
plt.imshow(img)
plt.show()


Found ckpts ['./logs/lego_example/020000.tar']
Reloading from ./logs/lego_example/020000.tar
Not ndc!
<function create_nerf.<locals>.<lambda> at 0x7fcaf7e675f0>
[[150.   0.  50.]
 [  0. 150.  50.]
 [  0.   0.   1.]]


TypeError: 'float' object cannot be interpreted as an integer